### ISSUE TITLE
Help in reproducing results

### ISSUE THREAD

**Issue by arunikayadav42** [nayeem8527/Chitra-VarNan#1]
Why is https://github.com/nayeem8527/Chitra-VarNan/blob/master/im2txt/data/build_hindi_mscoco_data.py#L447 commented . Don't we need the TF records of the train data? Please help me as I am trying to reproduce the results.

**Comment by nayeem8527** [comment]
Hi Arunika,

Please see the Readme of the repository carefully. Yes we do require TFRecord file of the training data as well but the script that you have to run is tfreader.py.

**Comment by arunikayadav42** [comment]
Thanks for pointing that out. I have produced the necessary to record files. can you please let me know what to set the variable TFRECORD FILE PATH in training the model. I have set it as the tf record directory path but its not the same as the file path and there are a lot of tf record files. So, can you suggest what to do?
